### ISSUE TITLE
font size changes when viewing a text file and rotating the screen

### ISSUE THREAD

**Issue by wizdude** [nextcloud/ios#338] opened 2017-08-09 11:23 UTC
if i display a text file, the font comes up small as expected.
rotate the screen clockwise and the font becomes large
rotate the screen anti-clockwise and the font stays large
rotate the screen clockwise and the font becomes small
rotate the screen anti-clockwise and the font stays small.

it toggles between the two font sizes, assuming you don't manually zoom in or out.

i kept repeating this and in one case the font went really large and the text file was no longer visible.
i can't reliably repeat this last part, however.

cheers, wizdude.

**Comment by rakekniven** [comment] 2017-08-19 07:32
Cannot confirm this with an iPad Pro.
Which device are you using?
Which app version?
Which iOS version?

**Comment by keitalbame** [comment] 2017-10-08 12:10
I can this change in font size behaviour some files, mostly (but not exclusively) on new ones.
For test I used the `Create text file` from the plus (+) sign on the NC ios app, on NC root or inside any folder.
Also tried creating the files from the NC desktop app and also see the change.
Sometimes, the text is not visible but if you scroll horizontally, you can see the text.

Like @wizdude mentioned, I only saw once, the really large font and no longer able to replicate.

iphone 7
nextcloud iOS 2.17.8
iOS 10.3.3

**Comment by johkoenig** [comment] 2020-11-28 00:44
cant reproduce. probably fixed in current version

**Closed by johkoenig** 2020-11-28 00:44 UTC
