### ISSUE TITLE
Share Link after Enforce Password Protection Not Working

### ISSUE THREAD

**Issue by togglecode** [nextcloud/ios#389] opened 2017-10-04 10:39 UTC
Server 12
iOS Version: 2.18.0 (6)

Steps to reproduce:

1. Enable "Enforce Password Protection" in admin pannel
![screen shot 2017-10-04 at 12 32 44](https://user-images.githubusercontent.com/17141698/31171518-45129efe-a900-11e7-987f-5c37fddff17a.png)

2. Open the iOS App, and try to share a file. The option will not work.

![sharelinkbug](https://user-images.githubusercontent.com/17141698/31171560-6fc1191e-a900-11e7-80fe-24d2ab19180f.gif)

**Comment by rakekniven** [comment] 2017-10-05 09:53
Did you try positiv test. Disable "enforce password protection" and share link? Does this work?

**Comment by togglecode** [comment] 2017-10-10 08:20
@rakekniven Yes of course, it works like that.

As a matter of fact it also works in this case if you type in a password in the password field above (in the gif I didn't type a password)

So basically what the App needs in future is just the error "Please type in a password", and also if the password needs a certain security. (This feature already exists on Android Version)

**Comment by togglecode** [comment] 2017-10-10 08:43
Related to issue [1089 on android](https://github.com/nextcloud/android/issues/1089).

**Comment by medcloud** [comment] 2019-02-20 20:21
Hello, 
I go back on this problem opened in 2017 because this bug seems still existing in 2019.
Moreover, the workaround found in 2017 (to type password before enabling the share button) doesn't seem to work anymore because in app version NextCloud for iOS v 2.23.0.0, you cannot enter any password until enabling the share button... which doesn't work. Thus, we cannot share.

Do you reproduce also same behaviour ? 

Thank you very much for your feedback.

**Comment by lostmap** [comment] 2019-09-26 14:24
Sadly, but this bug still exists. Is there any workaround or fix patch coming soon?

**Comment by marinofaggiana** [comment] 2019-09-28 12:13
Will be fixed in the next version on TestFlight

**Closed** 2019-10-09 06:37 UTC
Labels: bug
