### ISSUE TITLE
Nextcloud on iPad freezes!

### ISSUE THREAD

**Issue by lisetauber** [nextcloud/ios#1369] opened 2020-08-02 08:51 UTC
Hello,
Since the last update (3.0.2) for NC for iPad, the app freezes! It seems, this appears, as I want to delete a file directly on the server. 

Best regards
Lise
https://lise.tauber.fr/

**Comment by marinofaggiana** [comment] 2020-08-02 15:38
Hi ! I need moore data ... you can look the errors in Nextcloud log or the traffic generated ... if the app freezes probably some service(s) generate error (s)

**Comment by lisetauber** [comment] 2020-08-02 17:44
Hello Marino,
Thank you for your answer! 
I effectively installed Strongbox recently, both onto iPad and iPhone (after trying KeePassium, which doesn’t work with NC ; KeePassium doesn’t recognise the NC server). But I don’t encounter the same problem on the iPhone (version 3.0.1). I synchronise the database between KeePassXC on a Mac and iOS/iPadOS. 
I don’t notice any error in the activity log.
Lise

**Comment by lisetauber** [comment] 2020-08-02 19:36
I want to add, if I use another file app, I’ve no problem to access to the files, display them or transfer them! It seems, the problem comes from Nextcloud app ;-)

**Comment by marinofaggiana** [comment] 2020-08-03 10:33
I think that it's a issue of your NC iPad, Restore the application and reinstall, maybe can help you
cheers

**Comment by lisetauber** [comment] 2020-08-03 11:14
After uninstalling and restoring the app, it seems, it’s ok ;-) 
Thank you for your answers!

**Comment by lisetauber** [comment] 2020-08-03 12:26
It’s not ok ;-)

**Comment by lisetauber** [comment] 2020-08-03 12:33
Finally, it’s not OK ;-) after reinstalling, the app still freezes! I have to relaunch it, each time, it freezes. That happens since the update to 3.0.2.

**Comment by jacotec** [comment] 2020-08-04 08:53
I've had exactly the same issue after the upgrade to 3.0.2, also on my iPad Pro 10.5 ... iPhone worked.

Solved until now by deleting and reinstalling the app and I hope it continues to work ... but something seems to be wrong, at least when you update the app.

**Comment by koarlmichael** [comment] 2020-08-05 19:28
Same here on iPhone 7 IOS 13.6. Reinstalling didnt help.

**Comment by jacotec** [comment] 2020-08-05 20:56
Same issue also in the Testflight version 3.0.3.8. Sent a crash report after the app has died.

I hope this will be fixed ASAP

**Comment by jacotec** [comment] 2020-08-05 21:06
@marinofaggiana A full deinstallation and reinstall does not help anymore with 3.0.3.8 as well. 3.0.1 is unfortunately the last stable version. No hints in the logs of my server as well, seems to be a local app issue.

Let us know if we can help to track this down.

**Comment by 4d1830** [comment] 2020-08-06 06:06
I had this problem with iPhone also before latest version. Not only freeze but also keep CPU very intensive and low battery.

**Comment by marinofaggiana** [comment] 2020-08-06 10:26
> Same issue also in the Testflight version 3.0.3.8. Sent a crash report after the app has died.
> 
> I hope this will be fixed ASAP

Yes I have look your log but sorry the app do not start ... NO detail, somewhere got dirtied

**Comment by lisetauber** [comment] 2020-08-06 10:34
Hello, 
Would it be possible to (re)install a stable version (via TestFlight?). 
I tested the connection to our server  with other apps, with an ownCloud version too, and all the other apps work. It seems really, it comes from the 3.0.2! 
I have to use the Mac and the IPhone to access easily to the server, it’s a little laborious 😀 
Thank you in advance.
Lise

**Comment by crazybadger** [comment] 2020-08-06 13:02
Can anyone sign up to the Testflight testing, and is it possible to downgrade to 2.x?

**Comment by jacotec** [comment] 2020-08-06 14:33
@lisetauber Via Testflight you can install 3.0.1 ... valid for 62 days from today.

3.0.3(9) from today still no improvement ... 🙁

**Comment by marinofaggiana** [comment] 2020-08-06 14:36
@jacotec No, because I don't know where is the problem, you can tray from 1, 2 days with 3.0.3 available in Apple Store as stable.

**Comment by jacotec** [comment] 2020-08-06 14:38
OK ... how can we help you @marinofaggiana ?

**Comment by marinofaggiana** [comment] 2020-08-06 14:43
Do you have restart the phone ? Seems trivial but a lot of files remain in temp / dir of iPhone

**Comment by jacotec** [comment] 2020-08-06 14:56
No, I either closed or deleted and reinstalled the app, the latter should hopefully clean up the temp files.

The freeze is mostly temporary and happens mostly while selecting a folder in the files/folder tree. Even when entering a folder with just 4 subfolders and 3 files the complete app freezes for 5-10 seconds or even longer. It does not react to anything, it just stalls.

In 90% it recovers after some time (until you change again a folder or do some other action), in 10% the app crashes (or is suspended by IOS, I don't know).

When you are in a screen or folder idling around it does not happen. You need to change a folder or select any other menu.

I'll try an iPad restart as well.

**Comment by lisetauber** [comment] 2020-08-06 15:01
On the French AppStore, there is none update to 3.0.3 !

**@jacotec** Thank you for the proposition to upload a stable version from TestFlight, but I’ve no right for Nextcloud on TestFlight!

**Comment by lisetauber** [comment] 2020-08-06 15:12
Yes, I restart the IPad! 
On the French AppStore, the 3.0.2 is  still displayed, there is no 3.0.3!
And I’ve no right for Nextcloud app on TestFlight! 
![IMG_1489](https://user-images.githubusercontent.com/31109077/89548868-e1a0bd80-d807-11ea-918e-8fb6b1e902ea.jpeg)

**Comment by jacotec** [comment] 2020-08-06 15:14
@lisetauber https://testflight.apple.com/join/GjNbfo2a

**Comment by marinofaggiana** [comment] 2020-08-06 15:20
> No, I either closed or deleted and reinstalled the app, the latter should hopefully clean up the temp files.
> 
> The freeze is mostly temporary and happens mostly while selecting a folder in the files/folder tree. Even when entering a folder with just 4 subfolders and 3 files the complete app freezes for 5-10 seconds or even longer. It does not react to anything, it just stalls.
> 
> In 90% it recovers after some time (until you change again a folder or do some other action), in 10% the app crashes (or is suspended by IOS, I don't know).
> 
> When you are in a screen or folder idling around it does not happen. You need to change a folder or select any other menu.
> 
> And the issue was introduced between 3.0.1 and 3.0.2.
> 
> I'll try an iPad restart as well.

But this is different from the issue of @lisetauber ... please @jacotec if generate a crash please add a comment with "jacotec"

**Comment by lisetauber** [comment] 2020-08-06 15:23
Thanks, I just uploaded the 3.0.3 via TestFlight!

**Comment by jacotec** [comment] 2020-08-06 15:27
Not sure if it's different ... @lisetauber : When it freezes and you wait 30 seconds, can you operate it again?

@marinofaggiana My crash report from yesterday had jacotec in the email with which I've tagged it.

**Comment by lisetauber** [comment] 2020-08-06 15:29
@jacotec yes, with the 3.0.3, the app still freezes, but after a little while, I can operate again!

**Comment by jacotec** [comment] 2020-08-06 15:30
So it's exactly what I have @marinofaggiana

**Comment by lisetauber** [comment] 2020-08-06 16:05
With the 3.0.3, it’s a little better, the app freezes but after a little while, I can operate again. But for the first time, as NC turned in background, it crashed twice! I just send two reports. 

I’ve another bug: I modified folder names on the Mac, the new names are not all updated on the iPad (3.0.3). On the iPhone, with the 3.0.1, all folder names are correctly synchronised.

**Comment by jacotec** [comment] 2020-08-07 08:11
@lisetauber Please create a new issue for the "other bug"

**Comment by lisetauber** [comment] 2020-08-07 08:28
Done 😀

**Comment by jacotec** [comment] 2020-08-07 08:45
@marinofaggiana 
Some more infos: I have monitored the server connections and processes while using the iPad app. Changing into a folder gave me a 38 seconds long freeze of the app. In this time the php-fpm processes on the server went all to idle and no communication or data packets between the iPad and the server were seen.

After these 38 seconds the app became responsible again and fetched the data of the folder from the server.

Whatever is going on during the freeze seems not to be relating to the server as there is zero communication between the iDevice and the Nextcloud server.

Autouploads are switched off at our iPads, so there's also no relation to this which might trigger background activities.

We see it on our iPhones as well ... 4 out of 4 devices affected. I fear it's a widespread issue (only a few users usually find the way to Github)

Do you have a version with some debug logging where the logs from the app can be accessed or sent via a menu entry (i.e. in More --> Settings --> Extended) even without having the app crashed? I'm fully with you that you can't analyze it when you can't reproduce it, but let us help you to collect information for you ;-)

**Comment by crazybadger** [comment] 2020-08-07 12:11
I rolled back to 3.0.0 and don't experience this behaviour, so something was changed in 3.0.1 or 2 which broke this

**Comment by lisetauber** [comment] 2020-08-07 12:30
I encounter the same issue with the iPhone (iOS 13.6) with the 3.0.2. as with the iPad (iPadOS 13.6). The app freezes a little shorter on the iPhone.
I access to the files on the server from all other apps... either from the iPad or the iPhone.

**Comment by marinofaggiana** [comment] 2020-08-07 15:49
Find a possible issue, please wait the 3.0.4 build 1 in TestFlight

**Comment by jacotec** [comment] 2020-08-07 17:01
> Find a possible issue, please wait the 3.0.4 build 1 in TestFlight

Will definitely do and report!

**Comment by marinofaggiana** [comment] 2020-08-08 09:35
@lisetauber do you have create another account for look if the issue it's the same ?

Note: if yes you can send me the account ? at ios @ nextcloud . com

**Comment by lisetauber** [comment] 2020-08-08 11:53
Perhaps have you seen a crash log from Apple/TestFlight and from this email webmestre@tauber.fr; github@tauber.fr is an alias from webmestre@tauber.fr.

--
Lise
Mon blog perso
Nordique-Saint-Maurice

**Comment by jacotec** [comment] 2020-08-08 14:01
> Find a possible issue, please wait the 3.0.4 build 1 in TestFlight

@marinofaggiana I received the 3.0.4 in Testflight an hour ago, but it's tagged as 3.0.4.0 (and it still has the issue). You talk about 3.0.4.1, right? Do you have a plan when you want to put build 1 into Testflight, so we can check if it's fixed? 😉

**Comment by jacotec** [comment] 2020-08-08 14:27
@marinofaggiana OK, received 3.0.4.1 and unfortunately it's *not* fixed. Got 3 massive freezes within the first 5 minutes playing with the app. iPad was restarted after the update.

**Comment by jacotec** [comment] 2020-08-08 14:34
I've sent a crash report. I can immediately reproduce the issue on the iPad by:

- Dive 5-6 levels deep into a folders in "files"
- Then change randomly between the main menus: "More", "Favorites", "Media" and "Files".

Sometimes it freezes at the first section change, sometimes it needs a few to crash.

When you keep the app in the foreground, it normally recovers in 30-60 seconds.

When you put the app in background while it's frozen it crashes after a few seconds and you can send a crash report.

**Comment by lisetauber** [comment] 2020-08-08 14:47
Hello,
I installed the 3.0.4 (01) onto my iPhone 8 Plus (iOS 13,6). It crashed immediately. I tried another time to open it, it crashed again! I sent the crash log via TestFlight. 
I reinstalled the 3.0.1!

**Comment by marinofaggiana** [comment] 2020-08-08 15:27
Please someone send me an account test for debug, your crash log are empty .

**Comment by jacotec** [comment] 2020-08-08 15:29
What is an "account test"?

**Comment by marinofaggiana** [comment] 2020-08-08 15:30
An account in your server with this issue.

**Comment by jacotec** [comment] 2020-08-08 15:36
@marinofaggiana I've sent you credentials to ios@nextcloud.com

**Comment by marinofaggiana** [comment] 2020-08-08 15:38
@jacotec try you with this "my" account if you have the same issue.

**Comment by jacotec** [comment] 2020-08-08 15:49
@marinofaggiana Lol, it took me 3 Minutes to even log into your account because the app always froze even during entering the credentials for the new account (while still attached to my account).

Just with the "empty" account it does not happen! So I guess it needs some data to occur. Which leads me to the next idea: Maybe it's the amount of media files?

I don't think that it's the number of files and folders in the account ... I guess the app is not buffering the full directory listings and just display the dir listing when the folder is changed.

But I have roughly >8000 pictures and videos in my account (my wife >12000). I'm not sure if there is processing of the "Media" tab content in the app which leads to the freeze?

@lisetauber How many pix/videos do you have in your account?

**Comment by marinofaggiana** [comment] 2020-08-08 15:54
mmmm maybe .... [Open investigations Query Media n. max item return]

**Comment by marinofaggiana** [comment] 2020-08-08 16:02
@jacotec I will prepare a test version for this possible problem.

**Comment by marinofaggiana** [comment] 2020-08-08 16:14
Try, Build 2 ... when available.

**Comment by lisetauber** [comment] 2020-08-08 16:41
I tried both with the 3.0.4 build 0 and 1.  The twice crashed.
I reinstalled the build 1.
It freezes. Then, when the app turns in background, it crashes.
I just sent a crash log.

--
Bien cordialement
Lise TAUBER
Mon blog perso
Nordique-Saint-Maurice

**Comment by lisetauber** [comment] 2020-08-08 16:58
I retried both the builds 1 & 2, after rebooting the iPhone. Both freeze and then crash!

**Comment by lisetauber** [comment] 2020-08-08 17:04
I have  few videos, three in my account and 8, my brother shares with me!

**Comment by marinofaggiana** [comment] 2020-08-08 17:05
@lisetauber can you share with me the account ? ( ios @ nextcloud . com )

**Comment by jacotec** [comment] 2020-08-08 17:08
@marinofaggiana Build 2 still freezing, Media library is empty here, just saying "Search active" ...

**Comment by marinofaggiana** [comment] 2020-08-08 17:10
Sorry, without an account with this issue I can't continue.

**Comment by jacotec** [comment] 2020-08-08 17:51
@marinofaggiana Do you or the Nextcloud team have a set of test data I can upload to the test account on my server? Please understand that I can't share my account for testing as it contains very private documents and media.

Build 2 does not show or collect media files at all and still has the issue, I went back to build 1. Media thumbs were immediately back with it.

I'd review the changes between 3.0.1 and 3.0.2, that's where it was introduced. @lisetauber and I can confirm this.

What else can we do? I have a MacBook and my iPad has access to an Apple developer account, but I have no experience how to debug in XCode. I'd need a good documentation how to debug for you.

**Comment by marinofaggiana** [comment] 2020-08-08 18:11
It's implicate, don't worry sooner or later the fix will come

**Comment by jacotec** [comment] 2020-08-08 18:17
I just want to help 😊
Before 3.0.3 the autoupload was buggy, so I'd like to run 3.0.3+ as soon as possible 😉

Let me know when I can support you, Teamviewer Access to my Mac etc ... otherwise if you build a couple of test versions with the changes 3.0.1 <-> 3.0.2 reverted one by one I'm more than happy to test them all.

**Comment by marinofaggiana** [comment] 2020-08-09 11:11
Sorry all, but without your "account" (privacy) or with an account with this issue I can know the reason, the LOG do not help.

**Comment by jacotec** [comment] 2020-08-09 13:01
@marinofaggiana 
I'm still pretty convinced it's related to the media files!

I have deleted the app, restarted the iPad and reinstalled the latest Testflight version.

In the first minutes I had no(!) issues at all! All was smooth, but only a fraction of media was discovered on the media page. As more I used the app, just changing between folders and menus, as more it became less responsive and freezes are building up. It started with 2 second freezes, later around 5 seconds, now I'm at 10 seconds and still not all picture placeholders are on the media page.

Looks as if the media page (which seems to be cached / stored in the app) "overloads" the app / iDevice as bigger it grows. It's the only thing which builds up slowly after installation, and there is a direct relation between the numbers of media's fetched and the freezes.

That would also explain that the freezes are less long on our iPhones as they  are more powerful. iPhones are both iPhone 11 Pro Max, iPads are iPad Pro 10.5 and iPad Air 2.

It might be a good idea to have some pagination on the media page to have smaller pages built up. It's also not very user friendly to scroll thousands of pictures down if you search something in 2014 😉

**Comment by jacotec** [comment] 2020-08-09 13:31
Changed back to 3.0.1(18) in Testflight with the same data set - that's a dream! Responsive, not even a single tiny freeze.

I thought to test each single build in the 3.0.2 develop history to see at which point the issue was introduced, but the history is not available in test flight 🙁 Only the final 3.0.2(16).

**Comment by lisetauber** [comment] 2020-08-09 16:07
No change with the beta 4on the iPhone, even after a reboot.
I come back again to 3.0.1!

**Comment by marinofaggiana** [comment] 2020-08-09 16:49
@jacotec @lisetauber can you send me your email at ios @ nextcloud . com , Monday I want prepare a special version only for you in TestFlight.

THX

**Comment by jacotec** [comment] 2020-08-09 17:12
@marinofaggiana Done! Highly appreciated 😉

**Comment by lisetauber** [comment] 2020-08-11 09:43
@marinofaggiana

Hello Marino,
I re-test the last beta (3.0.4 -06) on the iPhone, after rebooting the phone. 
You must have receive the crash log, a littler earlier. As I open a file, the app freezes, and when the app is in background, crashes. 
I came back to the 3.0.1, which work correctly both on my iPhone 8 Plus on my iPad Air 3. 

PS. I answered to your precedent message and sent you my email.

**Comment by lisetauber** [comment] 2020-08-11 11:57
Thanks for this version! 
It works! On the iPhone, I could display photos and files. 
The app crashed on the iPad, as I tried to open an .ods file, I sent the crash log. 
I try a little bit more to verify, it’s ok.

**Comment by lisetauber** [comment] 2020-08-11 12:18
In fact, I think the app freezes, because of the access to the memory. 
As I tried to open a folder with documents (with pdf files), of 60Mo, the app freezes during 50 seconds! 
If I wait, without going to another app, the app doesn’t crash. 
However, the app crashes by opening an .ods file.

I retry with the 3.0.1, with the same folder, and the app doesn’t crash. 
If NC cannot open an .ods file, the app doesn’t freeze neither crash, I can share the file with another app.

**Comment by marinofaggiana** [comment] 2020-08-11 12:21
Probably problem with Database:

https://github.com/realm/realm-cocoa/issues/6577

**Comment by jacotec** [comment] 2020-08-11 12:26
From the first 5 minutes of testing, build 9 looks much better to me 🎉👍🏻!
But it's too early for a final hooray, I'll update tonight after more testing.

**Comment by lisetauber** [comment] 2020-08-11 12:27
As I came back to the 3.0.1 (both on iPhone and iPad), I had to enter login en password, NC disconnected from the cloud.

_`Probably problem with Database`_ and, what should I do ?

**Comment by marinofaggiana** [comment] 2020-08-11 12:31
Nothing... wait a fix ...

**Comment by jacotec** [comment] 2020-08-11 12:33
@marinofaggiana Unfortunately I was happy too early ... had three massive >30 sec freezes with build 9 🥺🥺

**Comment by jacotec** [comment] 2020-08-11 18:35
@marinofaggiana So you think the freeze is due to the mentioned database issue? Or is that a different one (the crash when it's in the background)?

The freeze always happened while the app runs in foreground, in my opinion the mentioned database issue is not happening?

**Comment by lisetauber** [comment] 2020-08-12 15:53
Hello Marino,

Thanks for this new beta (11), it seems to work! I can open files with différent formats, PDF, jpg, big files too, except .odt files and probably all other files from libre office. 
The app crashed only as I tried to open an .odt file (I sent the crash log from the iPhone). Otherwise, it seems, that the app doesn’t freeze anymore!

I’ll text now on the iPad! 😀

**Comment by lisetauber** [comment] 2020-08-12 16:07
It’s ok on the iPad Air too! the app  doesn’t freeze anymore, except a very short moment (one second) due probably to the device, which is not powerful enough!
The only crash, on the iPad too, happens as I want to open an .odt file. 

Thank you for the work, tou did!

**Comment by jacotec** [comment] 2020-08-12 16:43
Build 11 definitely looks improved here as well 😊
Got 1-2 10sec freezes at the iPad within the first ~3 Minutes, but let the app settle after the update. No issues in the last 10 minutes, will continue testing. 👍🏻

**Comment by jacotec** [comment] 2020-08-13 12:54
Got two 30 sec freezes today on the iPad, so it's not finally solved.

My wife got 4 nextcloud crash popups this morning even without using the app, maybe due to GPS based activation to check for photo upload.

Both with build 11 ...

**Comment by lisetauber** [comment] 2020-08-14 20:27
Beta 3.0.5

After a first crash just after the update on the iPhone, this new beta seems to work both on iPhone and iPad 😀 I can open different types of files, but it still crashes, when I open a Libre Office file. 
No freeze 😀  displays quickly all the files!
Thanks!

**Comment by dinony** [comment] 2020-08-16 20:37
I can confirm that the 3.0.1 is the last stable version for me. Newer versions hang after 10 seconds.. sent multiple crash reports. Hope it helps!

**Comment by jacotec** [comment] 2020-08-17 16:47
Dear @marinofaggiana , can you give us a small status update regarding this? Did you already create the "private test builds" for us? Or do you think also the freezes are related to the mentioned database issue and we need to wait for the next realm/cocoa release with the potential fix?

**Comment by lisetauber** [comment] 2020-08-17 17:19
Hello, 
I've until now 😀 no more freeze neither crash with the 3.0.5.4, except just after the installation onto the iPhone, and with Libre Office files. 
The app works without problem on my iPad Air and my iPhone 8 Plus.

**Comment by jacotec** [comment] 2020-08-17 17:36
No changes here, freezes like hell on all our devices (2xiPhone, 2xiPad). Deinstall, restart iPad, full new install - all does not help. Except using 3.0.1, which is not an option on our iPhones because of photo upload issues.

**Comment by lisetauber** [comment] 2020-08-18 08:56
Version 3.0.0.5
No more crash at the first launch on the iPhone, neither on the iPad, no freeze, no crash during displaying folders and files. 
Crashes only, as I try to open an odt file, or ods.

**Comment by jacotec** [comment] 2020-08-19 14:19
The fix in the latest Realm/Cocoa version 5.3.4 looks promising regarding the database issues:

> Fix a bug in memory mapping management. This bug could result in multiple different asserts as well as segfaults. In many cases stack backtraces would include members of the EncyptedFileMapping near the top - even if encryption was not used at all. In other cases asserts or crashes would be in methods reading an array header or array element. In all cases the application would terminate immediately. (Core #3838, since v5.0.0).

**Comment by lisetauber** [comment] 2020-08-19 21:28
I appear as no more able to test Nextcloud on TestFlight? Is it intentional?

**Comment by jacotec** [comment] 2020-08-19 21:32
It's fine here, just updated my wife's devices to 3.0.5(7) 15 minutes ago.

**Comment by marinofaggiana** [comment] 2020-08-20 08:02
> I appear as no more able to test Nextcloud on TestFlight? Is it intentional?

? Use the link https://testflight.apple.com/join/GjNbfo2a

**Comment by marinofaggiana** [comment] 2020-08-20 08:08
We can close this issue, reopen if exists new problems

**Closed by marinofaggiana** 2020-08-20 08:08 UTC

**Comment by jacotec** [comment] 2020-08-20 09:51
@marinofaggiana I suggest to reopen this ;-)

I've send you an internal log of a 40 seconds freeze with 3.0.5(7) by email with some thought what might happen. Please kindly check.

**Comment by lisetauber** [comment] 2020-08-20 10:25
Quick test with 3.0.5 (8) with iPad and iPhone.
No crash no freeze, also if I try to open Libre Office  files!
Thanks a lot !

**Comment by marinofaggiana** [comment] 2020-08-20 10:28
It's Freeze only for @jacotec because use too many file for a single dir (and isn't ad issue of iOS). So this issue remains closed. bye

**Comment by marinofaggiana** [comment] 2020-08-26 09:03
@lisetauber @jacotec resolved ?

**Comment by lisetauber** [comment] 2020-08-26 09:31
It seems 😀 I just downloaded the 3.0.6.8. 
Just a little thing, Touch ID is not always active on the iPad, I have sometimes to enter the code; and the app is not always locked (noticed with the 3.0.6.7),  although after relaunching the app or rebooting the device; no problem on the iPhone.

**Comment by marinofaggiana** [comment] 2020-08-26 09:35
it's an old iPad device ?

**Comment by jacotec** [comment] 2020-08-26 09:53
> @lisetauber @jacotec resolved ?

@marinofaggiana Looks good for me! 👍🏻😁🙏🏻

**Comment by marinofaggiana** [comment] 2020-08-26 09:54
Good thanks !

**Comment by lisetauber** [comment] 2020-08-26 10:38
@marinofaggiana 
The iPad is new ! An iPad Air 3, the iPhone a little older. An iPhone 8 Plus.
Le Blog de Lise is my blog 😀 [https://lise.tauber.fr/](https://lise.tauber.fr)

**Comment by marinofaggiana** [comment] 2020-08-26 13:14
@lisetauber I don't speak French, so I can't follow your blog ! sorry

**Comment by lisetauber** [comment] 2020-08-28 14:13
With 3.0.7.0, each time I open another app, when I quit NC, the app crashes, only on the iPad Air 3, not on the iPhone 8 Plus.
