### ISSUE TITLE
Blue Header-Bar with white Nextcloud Logo

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/ios#77] opened 2017-02-16 19:28 UTC
Should be blue with white fonts (and logo) instead of white with blue logo... what do you think?

![img_0441](https://cloud.githubusercontent.com/assets/19711361/23037412/866467b8-f486-11e6-9342-52dd69731c64.PNG)

@jancborchardt

**Comment by jancborchardt** [comment] 2017-02-19 21:29
Yes – duplicate of https://github.com/nextcloud/ios/issues/66 ;)

**Closed by jancborchardt** 2017-02-19 21:29 UTC
Labels: design, starter issue
