### ISSUE TITLE
Easier renaming in upload via Share Menu

### ISSUE THREAD

**Issue by thgoebel** [nextcloud/ios#1733] opened 2021-10-31 10:12 UTC
### Steps to reproduce

1. Click "Share" in another app and select Nextcloud in the Share Menu
2. Try to rename the file before upload

### Expected behaviour

A simple click on the filename should bring up the popup with the TextEdit field (1 step).

### Actual behaviour

I need to click the ... and then "Rename file" (2 steps).

### Screenshots

<img width="50%" src="https://user-images.githubusercontent.com/33295590/139577640-d943b94a-fab5-41f9-a2e1-e5b5bca960f8.png">

### Reasoning or why should it be changed/implemented?

1. The action in uncessarily hidden away.
2. Clicking on the file name to change it is natural.
3. Why is the ... menu even needed? In what situation would I need to *delete* a file that I am *uploading*? Where would it even be deleted from? The 3rd app that I am sharing it from?? The Nextcloud server - where it most likely does not exist yet??

### Environment data

**iOS version:** iPadOS 15,1

**Nextcloud iOS app version:** 4.0.6.0

**Comment by thisIsTheFoxe** [comment] 2021-11-05 12:16
Hi,
Thank you for your feedback. And I can see how we might be able to simplify the renaming process.

About your 3rd point, *"Remove file"* would probably fit a lot better here. Because it is possible to share multiple files at once. E.g. in the iOS Files.app -> "..." -> Select -> Share. In that case you can remove some of the files you previously selected and still share the rest of them without going back. When sharing a single file, it is somewhat unnecessary since it does the same as "Cancel".

**Comment by marinofaggiana** [comment] 2021-11-05 13:00
I confirm the delete file is a very good option which does not bother. I think we can close this issue

**Comment by thgoebel** [comment] 2021-11-06 08:34
I absolutely agree with you that the remove action makes sense!
Still, the fact that I didn't get it means that it is probably worth renaming "Delete file" -> "Remove file" to make more clear what it does :). Note that making sure that all translations are renamed might be tedious. :grimacing: 

Some other ideas for the UX (I would love the renaming to be more easily accessible!):

Idea 1:
- Rename: by clicking on the file name.
- Remove: by clicking on a dedicated icon (e.g. Ⓧ or 🗑️).
- Pros: fastest. 1 click for both actions.
- Cons: Icons-only, no explicit text. And for my not-really-technologically-versed parents it might be not intuitive to click on the file name to change it.
<img width="50%" alt="nextcloud-upload-rename-2" src="https://user-images.githubusercontent.com/33295590/140602916-cdd5a154-3305-4577-9671-1c595ea91395.png">

Idea 2:
- Rename: by clicking on the file name.
- Remove: by swiping from-right-to-left (classic iOS-syle, with the red background).
- Pros: 1 click for renaming, 1 long swipe (or 1 short swipe + 1 click) to remove.
- Cons: Remove action is even more hidden - but arguably more iOS-native?
<img width="50%" alt="nextcloud-upload-rename-3" src="https://user-images.githubusercontent.com/33295590/140603064-0ac9ba8c-c3e8-408d-b13c-cb57efd85bf0.png">

Idea 3:
- Keep the ...-menu as is (just rename "Delete file" -> "Remove file").
- Rename: also by clicking on the file name. (I.e. now there are 2 ways to rename).
- Pros: keeps current behaviour while making renaming easier for digital-native users (who want to click on it rather than going through menus :innocent: ).
- Cons: 2 ways to achieve the same action (rename) can be confusing?

**Comment by thisIsTheFoxe** [comment] 2021-11-08 07:49
@thgoebel I totally agree. And *Idea 1* was what I was thinking about too. Just instead of clicking on the file name it should probably be the whole row, since there's no other action that would make sense (imo) and it increases the tap target. Except, maybe a preview, which the rename alert provides anyway.

**Comment by jancborchardt** [comment] 2021-12-29 11:07
Great points @thgoebel – your idea 3 makes most sense design-wise. :)

Additionally, in the action menu, "Remove file" should be on the bottom of the list (as we always put destructive actions on the bottom) and marked with red text color if possible.


> Idea 3:
> - Keep the ...-menu as is (just rename "Delete file" -> "Remove file").
> - Rename: also by clicking on the file name. (I.e. now there are 2 ways to rename).
> - Pros: keeps current behaviour while making renaming easier for digital-native users (who want to click on it rather than going through menus :innocent: ).
> - Cons: 2 ways to achieve the same action (rename) can be confusing?
>

**Comment by thisIsTheFoxe** [comment] 2021-12-29 12:37
Thanks for the insight @jancborchardt 
But I wouldn't actually classify the "removing" as a destructive action. It just 'deselects' the files from being uploaded, it doesn't _destroy_ them. If you do it by mistake you can easily cancel and reopen the menu and be back where you started. (And yes,  maybe it's worth the thought of actually making the rows selectable instead of removing them altogether..)

That's why, personally, I prefer a simple (x) button.. The menu together with words like "delete" and "remove" just give the action more severity than it deserves, imo.

**Comment by jancborchardt** [comment] 2021-12-29 13:19
The problem is that if we just have an x icon on the right, it won't be obvious that renaming is even possible.
With the 2 actions menu and the tappability of the row for rename we have the obviousness with labels, as well as the shortcut for more advanced users as @thgoebel said.

Regarding sorting of "destructive action": Remove and delete are both considered destructive as they undo/remove/destroy what you did before, so we always sort actions like these to the botton.

**Comment by thisIsTheFoxe** [comment] 2022-01-05 10:31
@jancborchardt thanks again, I just kinda really dislike that menu 😅
What about the selectable idea? I.e. like in the app itself you'd have a round icon to the left that either has a filled checkmark or not. Then we could replace the current "..." icon with a pen icon to indicate you can also edit the name. Wdyt?

Also, I'm sorry if I was unclear.. I don't have a particular problem with the reordering itself. But labelling the button as 'destructive' and making it red would again increase its severity imo. And when handling important files users might be scared to "destroy" the files, even tho it's impossible to do that from there.

**Comment by jancborchardt** [comment] 2022-01-05 13:17
> What about the selectable idea? I.e. like in the app itself you'd have a round icon to the left that either has a filled checkmark or not.

Since the list is already the "files which are picked for upload", having checkmarks there would introduce another level and be confusing as to what that means. Everything would be checked by default anyway. It’s much clearer to have the specific actions.

As said, for normal folks we have the menu with actions, and for experts we can have shortcuts, and the 2 we can have are:
- Rename: By tapping anywhere on the row/filename except the 3-dot menu area.
- Remove: By swiping the entry to the left.


> But labelling the button as 'destructive' and making it red would again increase its severity imo. And when handling important files users might be scared to "destroy" the files, even tho it's impossible to do that from there.

You’re right, we shouldn’t make it red, as it’s indeed not so dangerous of an action. :) That’s why it would get an x-icon and be called "Remove file" (instead of "Delete file"). But still it should be last in the list of actions.

**Closed** 2022-01-18 09:05 UTC
