### ISSUE TITLE
ONLYOFFICE - iOS App hides UI Elements on newer devices

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#2444] opened 2023-05-30 09:47 UTC
The iOS hides some UI elements of the OnlyOffice Inegration in the iOS Client.
To be precise: The lower area, where you can add new page to a spreadsheet or switch pages is hidden behind another element.

See attached screenshots. One is made with the iPhone 14 Emulator, where the overall Display Design an UX is different to the older Display Designs like iPhone SE.
As you can see, the very same iOS App Build acts different. On newer devices (probably same for iPad) the UI elements hide other elements.
![Attachment file 1 Simulator Screenshot - iPhone SE (3rd generation) - 2023-05-30 at 10 58 46](https://github.com/nextcloud/ios/assets/8616947/e0b5c92d-3996-4821-8cdf-c67211b8dff1)

![Attachment file 2 Simulator Screenshot - iPhone 14 - 2023-05-30 at 10 50 19](https://github.com/nextcloud/ios/assets/8616947/6c3fff1b-6887-4269-9f07-efef4947314d)

**Comment by p-klassen** [comment] 2023-06-09 09:22
Hi! Anything new on this one?

**Comment by mpivchev** [comment] 2023-06-23 17:21
I can't reproduce it, but i do see some problems. In my case, the pages etc. show, but i have a weird empty space at the bottom, along with even more empty space.

Tested on iPad 6th gen.

![image](https://github.com/nextcloud/ios/assets/6960329/a5697e62-52f4-47ba-a0a7-c5351134d6ae)


Our WebView in the app is fullscreen, but I can see these WKCompositingViews are rendering the file, and they don't seem to render it properly. This is most likely an issue with Onlyoffice, and out of scope for us.

<img width="1470" alt="image" src="https://github.com/nextcloud/ios/assets/6960329/aefa0fc1-c8bd-47ef-a81a-f18160c6ba24">

**Comment by mpivchev** [comment] 2023-06-23 17:36
I tried adding this, but to no effect.

```
        webView.scrollView.contentInset = .zero
        webView.scrollView.contentInsetAdjustmentBehavior = .never
```

**Comment by mpivchev** [comment] 2023-06-23 17:46
Offsetting some of the webview to the bottom removes this empty space. However this is a hack and I still believe the issue is how the web app is rendered.

And I still can't reproduce a case where the bottom part (pages etc) are cut off. @marinofaggiana 

```
        bottomConstraint = webView.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: 70)
```

        bottomConstraint = webView.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: 70)

**Closed** 2023-06-29 16:25 UTC
Labels: 2. developing, bug, needs follow up

**Comment by curiousbarbarian** [comment] 2024-06-21 13:50
I experience the same problem on latest AIO in IOS 17.5.1. Any workaround?
