### ISSUE TITLE
One search triggers 5 SEARCH requests

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/ios#127] opened 2017-03-22 06:25 UTC
* open search
* type in a word
* click "search"
* expected: exactly one search request
* actual: 5 requests (that are 4 too much 😉 )

```
1.1.1.1 - morris [22/Mar/2017:06:20:45 +0000] "SEARCH /remote.php/dav HTTP/1.1" 207 1819 "-" "Mozilla/5.0 (iOS) Nextcloud-iOS/2.17" 373089
1.1.1.1 - morris [22/Mar/2017:06:20:45 +0000] "SEARCH /remote.php/dav HTTP/1.1" 207 1808 "-" "Mozilla/5.0 (iOS) Nextcloud-iOS/2.17" 372223
1.1.1.1 - morris [22/Mar/2017:06:20:45 +0000] "SEARCH /remote.php/dav HTTP/1.1" 207 1814 "-" "Mozilla/5.0 (iOS) Nextcloud-iOS/2.17" 383683
1.1.1.1 - morris [22/Mar/2017:06:20:45 +0000] "SEARCH /remote.php/dav HTTP/1.1" 207 1804 "-" "Mozilla/5.0 (iOS) Nextcloud-iOS/2.17" 392735
1.1.1.1 - morris [22/Mar/2017:06:20:45 +0000] "SEARCH /remote.php/dav HTTP/1.1" 207 1798 "-" "Mozilla/5.0 (iOS) Nextcloud-iOS/2.17" 442442
```

**Comment by jancborchardt** [comment] 2017-03-29 09:46
@marinofaggiana please don’t remove the »bug« label for any issues. Every issue should have either `bug` or `enhancement`. When the issue is fixed (pull request merged), then the issue can be closed. The labels should stay in place though.

**Comment by mario** [comment] 2017-07-29 19:23
So is this fixed now/ can be closed? :)

**Comment by marinofaggiana** [comment] 2017-07-30 13:56
yes fixed.

**Closed by marinofaggiana** 2017-07-30 13:56 UTC
Labels: 3. to review, bug, green
