### ISSUE TITLE
App is broken on iOS 11.0.1

### ISSUE THREAD

**Issue by notjoe** [nextcloud/ios#387] opened 2017-10-02 06:41 UTC
I try to login using the right information and i am given the following error message:

"It is not possible to connect to the server at this time. (null)"

I can successfully login with the android app and iOS 10 clients.

To be exact, iOS 11.0.1 With the iPhone 8Plus

**Comment by marinofaggiana** [comment] 2017-10-02 11:15
11.1 ... I think ?

**Comment by rakekniven** [comment] 2017-10-05 09:52
Testflight versions are working pretty well with iOS11.

The next version v2.18.0 should be ready for iOS11 and help you.

Which app version are you using?

Have an iPhone SE with iOS11.0.2 and app v2.17.8. It works.
Would you mind trying to uninstall app and reinstalling it?

**Comment by rakekniven** [comment] 2017-10-05 14:33
Hey @notjoe Are you willing to try Testflight (Beta) version?

**Comment by tcm300** [comment] 2017-10-15 19:40
Hi
I've a friend with the same problem on my nextcloud.
How to take part with the Beta Version?

**Comment by nuxnix** [comment] 2017-10-16 22:55
Same issue. iPad Pro. 11.0.2 shortly to be 11.0.3 Very happy to help in Testflight testing angusf at multizone dot co dot uk

**Comment by notjoe** [comment] 2017-10-17 06:59
@rakekniven absolutely. send me an invite. joe at fasti.net . 

Cheers

**Comment by rakekniven** [comment] 2017-10-17 18:08
@marinofaggiana would you please send TestFlight invitation?

**Comment by tcm300** [comment] 2017-10-17 20:25
@marinofaggiana @rakekniven 
please to timjames dot leu at gmail.com

**Comment by marinofaggiana** [comment] 2017-10-18 17:14
yes soon a new version beta available but : 

"It is not possible to connect to the server at this time. (null)"

Is strange (null) !! ... can with reinstall.

**Comment by rakekniven** [comment] 2017-11-01 14:42
@notjoe Any update from your side?

**Comment by tcm300** [comment] 2017-11-06 19:22
@rakekniven Hmm, it didn't helped for my friend. Still not possible to connect to a 11.0.5-Server :-(.

**Comment by andyxh** [comment] 2017-11-15 18:52
Hello, How can I join Testflight ? It's asking for a invitation code?

**Comment by rakekniven** [comment] 2017-11-17 21:05
@andyxh There is no Testflight available at the moment. It will be announced here as separate issue.

**Comment by Xarin** [comment] 2017-11-18 23:57
I also seem to be having this issue on a 12.0.3 Nextcloud server. Are there any workarounds at the moment?

**Comment by rakekniven** [comment] 2017-11-21 08:57
@andyxh For Testflight version see #412

**Comment by btorresgil** [comment] 2017-12-14 20:09
Hitting similar issue when trying to login.  Is this related, or new issue?

NextCloud 12.0.4
iOS App 2.18.2

Affects two of my devices:
iOS 11.2 on iPhone X
iOS 11.1.2 on iPad Air 2

I also noticed the iPad was already logged in from a previous iOS version and was still working with NextCloud, but once I log out, I hit this issue and can't login again.

![img_0187](https://user-images.githubusercontent.com/4164289/34011934-b51560f8-e0c6-11e7-8b63-c7c1ad2701b8.PNG)

**Comment by vistalba** [comment] 2017-12-22 22:18
Same here. Changed Password on WebGUI. After that no login is posdible with the iOS app. After a lot of tries login worked but now I‘ve loading issues for listings :( unusable.

Webbrowser on the same iPhone works without issue.

Server: nextcloud docker latest
IOS: 11.2

**Comment by klickagent** [comment] 2018-01-01 16:26
Same issue here. Maybe because I changed the password in the webgui as well. Cannot log in. Error: "It is not possible to connect to the server at this time. Check server error 0". Using the nextcloud app on Android works perfectly. Using the Owncloud App on iOS works perfectly for my Nextcloud Server installation as well.

**Comment by tcm300** [comment] 2018-01-01 18:02
Thanks for the hint!! Owncloud app works as well.
I cannot understand why it is that difficult to fix the Nextcloud app.

**Comment by marinofaggiana** [comment] 2018-01-02 10:28
Hi boys, please more info for this issue, I don't understand why this ... thanks

**Comment by vistalba** [comment] 2018-01-02 13:46
@marinofaggiana: is there a way we can provide logs or something that would help you to find out where the issue is? 

For me, it appears randomly, dont know why. Last time as I changed the password on webGUI.
After the change I was not able to login again. I tried it maybe 50 times... and then it worked... but all was verry slow. At the next day the issue was disappeared. :-(

**Comment by marinofaggiana** [comment] 2018-01-02 13:50
Sorry ... I need a "stable" issue ... without problem of network or other ...

**Comment by vistalba** [comment] 2018-01-02 14:05
This is not a network related issue. WebGUI on the same iPhone works without problems. 

It is an issue with the App. Android App and Owncloud App is also working at the same time.

**Comment by btorresgil** [comment] 2018-01-02 15:47
Indeed this is a very stable and consistent issue, easily reproducible and impossible to workaround as far as we know.  We are anxious for a fix as Nextcloud is unusable until we get one. Please tell us what to send you for debugging and I’m sure we will all be more than happy to provide it.

**Comment by marinofaggiana** [comment] 2018-01-02 15:56
@btorresgil example have you look the oc_bruteforce_attempts ? if this issue is riproducibile can you create for me a account test ?

**Comment by tcm300** [comment] 2018-01-03 20:58
Server: 12.0.4, no logs in the admin panel
iOS: 11.2.1
App: 2.19.1
Error:
![image](https://user-images.githubusercontent.com/28918397/34539536-256ce28a-f0d1-11e7-855f-c45c586f3e2d.jpeg)

**Comment by dvenckus** [comment] 2018-01-11 18:03
Same problem with the ios app as @tcm300.  Requests from the app are making it through to the server and the server is responding HTTP 200 OK.  

HEAD /remote.php/webdav HTTP/1.0

**Comment by dvenckus** [comment] 2018-01-11 18:29
I disabled the following line from the nginx hosts conf file and reloaded nginx:

add_header Strict-Transport-Security "max-age=15768000;

The iOS app began working.

**Comment by marinofaggiana** [comment] 2018-01-12 11:04
Please boy test with new login web flow (now in TestFlight)

**Comment by royvandongen** [comment] 2018-01-12 22:51
Can Confirm, Disabling my "HSTS Header"  fixed this.

My setup NextCloud 12, Ubuntu 16.04, PHP7.0-FPM, MariaDB, NGINX.

**Comment by tcm300** [comment] 2018-01-12 22:53
I can confirm that the new Testflight App works without any changes on the server! Big thanks!

**Comment by andyxh** [comment] 2018-01-12 22:53
There must be something in your configuration then. I have HSTS on and no issues

Sent from my iPhone 7 Plus

On Jan 12, 2018, at 4:51 PM, Roy van Dongen <notifications@github.com<mailto:notifications@github.com>> wrote:


Can Confirm, Disabling my "HSTS Header" fixed this.

My setup NextCloud 12, Ubuntu 16.04, PHP7.0-FPM, MariaDB, NGINX.

**Comment by marbetschar** [comment] 2018-01-20 00:39
getting access to TestFlight would be highly appreciated to figure out if #469 is fixed: apple@marco.betschart.name

**Comment by dvenckus** [comment] 2018-01-20 01:33
How do I get a Test flight invite/access?

**Comment by rakekniven** [comment] 2018-01-20 10:07
@dvenckus Please see #449

**Comment by instantlinux** [comment] 2018-01-24 06:21
iOS app quit photo-sync after 2.19.1 update 4 days ago on just one of the two mobile devices I've got set up for sync to a 12.0.4 server. Shows up as about 80 images/videos pending to upload, but nothing happens. In server logs I see the app logging in OK but then it makes no attempt to start sync. The app has no button to force sync (I think it should) so all I can do is post a report here. 

It's not robust; the problem I've often had is that one or the other devices will silently turn off auto-upload (separate problem I've seen reported here); that pretty much always happens whenever I update iOS or the app, but there are probably other triggers for that problem.

**Comment by marinofaggiana** [comment] 2018-01-25 20:20
Plase do not mix the issue. I close this

**Closed by marinofaggiana** 2018-01-25 20:20 UTC
Labels: bug

**Comment by instantlinux** [comment] 2018-01-25 22:08
I'd opena . new issue about the "nothing happens" after 2.19.1 update--but I really don't have any steps-to-repro information to provide.
