### ISSUE TITLE
Embedded images not loaded inside Notes

### ISSUE THREAD

**Issue by pjft** [nextcloud/ios#2813] opened 2024-02-27 09:23 UTC
### Steps to reproduce

1. Open note with images

### Expected behaviour

Embedded images should render inside the note, at the right location.

### Actual behaviour

Image placeholder shows up with error 500.

### Screenshots

![unnamed (6)](https://github.com/nextcloud/ios/assets/22025709/0a5c4186-9f33-4af3-a345-dbbd9adf8fcd)

### Logs

```
[index] Error: Exception: Call to a member function getUID() on null in file '/var/www/html/nextcloud/apps/text/lib/Service/AttachmentService.php' line 434 at <<closure>>

0. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /var/www/html/nextcloud/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main()
2. /var/www/html/nextcloud/lib/base.php line 1068
   OC\Route\Router->match()
3. /var/www/html/nextcloud/index.php line 38
   OC::handleRequest()

Caused by:

Error: Call to a member function getUID() on null at <<closure>>

0. /var/www/html/nextcloud/apps/text/lib/Service/AttachmentService.php line 226
   OCA\Text\Service\AttachmentService->getAttachmentDirectoryForFile()
1. /var/www/html/nextcloud/apps/text/lib/Controller/AttachmentController.php line 101
   OCA\Text\Service\AttachmentService->getAttachmentList()
2. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 230
   OCA\Text\Controller\AttachmentController->getAttachmentList()
3. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 137
   OC\AppFramework\Http\Dispatcher->executeController()
4. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch()
5. /var/www/html/nextcloud/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main()
6. /var/www/html/nextcloud/lib/base.php line 1068
   OC\Route\Router->match()
7. /var/www/html/nextcloud/index.php line 38
   OC::handleRequest()

POST /index.php/apps/text/attachments
```

### Reasoning or why should it be changed/implemented?

Well, it's a bug.

### Environment data

**iOS version:** iOS 

**Nextcloud iOS app version:** 

5.2.0.2

**Server operating system:**

Linux 6.1.66, ARM64

**Web server:**

Apache 

**Database:**

MySQL

**PHP version:**

8.2.7

**Nextcloud version:** 

27.1.6

**Comment by pjft** [comment] 2024-02-27 09:38
It seems that the changes from 3 months ago might have impacted this: 

https://github.com/nextcloud/text/commits/main/lib/Service/AttachmentService.php

**Comment by joshtrichards** [comment] 2024-08-02 19:39
Duplicate of nextcloud/text#5419

**Closed by joshtrichards** 2024-08-02 19:39 UTC
Labels: bug
