### ISSUE TITLE
Excel file view: changing sheets is not possible

### ISSUE THREAD

**Issue by mr-manuel** [nextcloud/ios#267] opened 2017-06-08 17:08 UTC
Hi,
when I open a Excel sheet in Nextcloud I can view only the first sheet and I'm not able to change to a second/third sheet. In a previous version (unfortunately I can't remember which) it did work.

**Comment by rakekniven** [comment] 2017-06-09 19:46
Please name version you are using.

**Comment by mr-manuel** [comment] 2017-06-09 20:05
Sorry, version is 2.17.4(8)

**Comment by sirio81** [comment] 2017-06-20 07:48
I confirm the same problem

Nextcloud client 2.17.3
Docs To Go: 5.3.6
iOS 10.3.2.

**Comment by marinofaggiana** [comment] 2017-08-04 14:20
Verify with 2.17.6

**Comment by mr-manuel** [comment] 2017-08-17 19:37
I have updated to 2.17.6 (11) and it is not working. When I press on the register cards nothing happens. I tried in full screen and normal mode. Also cleaned cache, uninstalled app completely and installed again.

**Comment by marinofaggiana** [comment] 2017-08-17 20:11
@mr-manuel  Nextcloud iOS use the internal view of iOS (web view), use you the Microsoft Excel App for a more complete compatibility.

**Comment by dimelo0918** [comment] 2017-08-22 21:28
Same issue here. does anyone know if this will be fixed to where we don't have to download another app to view the files and multiple tabs>

**Comment by mr-manuel** [comment] 2017-08-23 05:36
I've tested also with iOS 11 and there is the same issue... I opened a Bug report on Apples side :)

**Comment by marinofaggiana** [comment] 2017-08-23 09:21
@mr-manuel this is not a bug but a limit ... Excel is a Microsoft program use the Excel for iOS, why not ?

**Closed** 2022-08-08 14:59 UTC
