### ISSUE TITLE
Open nextcloud links (eg internal links) direct in the nextcloud app

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/ios#1779] opened 2021-11-30 10:35 UTC
It would be super awesome if internal links could be open direct in the nextcloud app instead of the browser. 

Imagine the following: User 1 sends User 2 a message with an internal link to a document. User 1 clicks on the document and comes to the browser and has to log in, but does not know his data, ...

Here is, how the talk-ios app implemented it: https://github.com/nextcloud/talk-ios/pull/671

**Comment by thisIsTheFoxe** [comment] 2021-11-30 11:08
Hi @jakobroehrl and thanks for the idea.
However, this looks like a duplicate. Please check out the linked issue. If it isn't feel free to reopen this issue and elaborate on your idea. If it is, the problem would be that *your* (or anyone else's) NC server URL would have to be known to the app beforehand.

Btw, also note that it is already possible to deep link into the app using the `nextcloud://` URI scheme as described in the linked issue.

### Possible duplicate of:
- #771

**Closed by thisIsTheFoxe** 2021-11-30 11:08 UTC

**Comment by jakobroehrl** [comment] 2021-12-02 11:29
Thanks for your reply. 
It's a duplicate, sorry.

> the problem would be that _your_ (or anyone else's) NC server URL would have to be known to the app beforehand.

But why it's working an Android since quite some time?

**Comment by thisIsTheFoxe** [comment] 2021-12-02 18:02
No problem :)

In Android it's possible to match a specific path for all (aka wildcard) domains (see [nextcloud/android](https://github.com/nextcloud/android/blob/5171d73285fcd5c19f534eda1a2077c4644821e1/src/main/AndroidManifest.xml#L108-L114)).
If you want to dig deeper check out the [Android docs](https://developer.android.com/training/app-links) and the [Apple docs](https://developer.apple.com/documentation/xcode/allowing-apps-and-websites-to-link-to-your-content?preferredLanguage=occ) about *Universal Links*.
