### ISSUE TITLE
[Feature request] Search inside text files

### ISSUE THREAD

**Issue by keitalbame** [nextcloud/ios#392] opened 2017-10-08 13:04 UTC
As mentioned on [this](https://github.com/nextcloud/android/issues/211) Android NC client issue, it would be useful to search inside plain text files, like txt, md, etc.

My use case is search several files that I use as my "wiki".

At the moment, the search function only searches for filenames.

**Comment by wiswedel** [comment] 2019-06-06 11:11
Duplicate of #873

**Closed by wiswedel** 2019-06-06 11:11 UTC
