### ISSUE TITLE
Whatsapp duplicated images skipped at upload

### ISSUE THREAD

**Issue by adrhc** [nextcloud/ios#2392] opened 2023-04-08 20:32 UTC
### Steps to reproduce

1. select (aka click) a contact in Whatsapp
2. select contact name at the top of the messages panel
3. select "Media, Links, and Documents" menu entry
4. stay on the "Media" panel (by default opened)
5. select few images then try to upload to Nextcloud app
6. check the number of "Images" before picking the Nextcloud app (e.g. "6 Images")
7. pick the Nextcloud app
8. check the number of "Files" (e.g. "Upload 4 Files") before pressing the upload button

### Expected behaviour

The number of "Images" before picking the Nextcloud application for uploading them should be equal to the number of "Files" presented on the button that triggers the upload.

### Actual behaviour

Sometimes, somehow, the images to upload (but not the already present ones at destination!) are detected as having the same name thus some of them are simply discarded from the upload list despite the fact that they are distinct images (i.e. iPhone presents different name for them). If one is able to identify the missed so considered, "duplicates", and try to upload them 1 by 1, Nextcloud identify them as already uploaded and permits the upload with a different auto-generated name, e.g. PHOTO-2019-03-19-15-22-49 1.jpg if PHOTO-2019-03-19-15-22-49.jpg was already uploaded.

Workaround: instead of picking Nextcloud application for upload (or any other application) one could slide lower to the “Save to Files” menu then could navigate to Nextcloud in Locations menu group and then select Save (up, right) which will save all selected images (presented at save as, e.g. “6 Items”). The problem with this approach is that one would have then to clear the Nextcloud application cache to reclaim the used space in Files because besides being uploaded, the saved items (i.e. images) will also be stored in Files.

### Environment data

**iOS version:** iOS 16.4.1 (20E252)

**Nextcloud iOS app version:** 4.8.0.5

**Server operating system:** Ubuntu 22.10

**Web server:** nginx

**Database:** 8.0.32-0ubuntu0.22.10.2 for Linux on x86_64

**PHP version:** PHP 8.1.7-1ubuntu3.3 (cli) (built: Feb 22 2023 22:55:33) (NTS)

**Nextcloud version:** 26.0.0

**Example images:**
![PHOTO-2019-03-19-15-22-49 1](https://user-images.githubusercontent.com/5136846/230741533-b03ed423-949d-4c41-b52d-64c04bcf741d.jpg)
![PHOTO-2019-03-19-15-22-49 2](https://user-images.githubusercontent.com/5136846/230741535-d4778332-b501-4352-9213-fcf76487280c.jpg)
![PHOTO-2019-03-19-15-22-49](https://user-images.githubusercontent.com/5136846/230741537-e0abd47e-3b69-444f-808d-e85acc206902.jpg)

**Comment by eharris** [comment] 2023-05-04 00:42
I believe this is a duplicate of #1835

**Comment by mpivchev** [comment] 2023-06-09 15:11
Thanks for reporting this, I tested it myself and I can reproduce it.

**Comment by mpivchev** [comment] 2023-06-09 17:06
Added PR with the fix

**Closed** 2023-06-22 16:59 UTC
Labels: 3. to review, bug
